services:
  mysql:
    image: 'mysql:8.0.39'
    environment:
      - 'MYSQL_DATABASE=courses'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'